[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery_solana = "5XL1aVpxSeQPq8WQnNAVgxs9XMGBf4NHaNVW3Gihq6xi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
